### ISSUE TITLE
If ~/.pq doesn't exist, the resulting error message is unhelpful

### ISSUE THREAD

**Issue by tokenrove** [sevagh/pqrs#35]
Would be nice to be a little clearer; currently we get:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sevagh** [comment]
This should be better now: https://github.com/sevagh/pqrs/commit/c8170b013eb2c167861e00b50c326a43b115768d#diff-aa7fddb39760f881304f2ec31ca05ac5R78

**Comment by tokenrove** [comment]
Thanks.  It might be nice if it said what path it expected, but it's good enough for me.

**Comment by sevagh** [comment]
I tried the paradigm of short message in `Error.description()` and long message in `impl Display`, but in main.rs I invoke `description()` for some reason. Probably better for usability to show the long messages.

**Comment by sevagh** [comment]
Funnily enough I even had unit tests for error message verbosity (which now fail):

```
running 7 tests
test test_no_fdset_files ... FAILED
test test_bad_input ... FAILED
test test_nonexistent_fdset_dir ... FAILED
```

**Comment by sevagh** [comment]
This should be better now with version 0.3.6. Releasing the `0.3.6` binary as we speak but it's published on crates.io:

```
sevagh:pqrs $ ./target/debug/pq
Path /home/sevagh/.pq doesn't exist

sevagh:pqrs $
```
